# Generated by Django 4.2.5 on 2023-11-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_image_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default1.jpg", upload_to="post_images"),
        ),
    ]
