# Generated by Django 4.2.6 on 2023-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default1.jpg', upload_to='post_images'),
        ),
    ]
